// automatically generated by stateify.

package boot

import (
	"context"

	"gvisor.dev/gvisor/pkg/state"
)

func (c *sandboxNetstackCreator) StateTypeName() string {
	return "runsc/boot.sandboxNetstackCreator"
}

func (c *sandboxNetstackCreator) StateFields() []string {
	return []string{
		"clock",
		"allowPacketEndpointWrite",
		"allowLiveTCPMigration",
		"uid",
		"egressFD",
		"egressGated",
	}
}

func (c *sandboxNetstackCreator) beforeSave() {}

// +checklocksignore
func (c *sandboxNetstackCreator) StateSave(stateSinkObject state.Sink) {
	c.beforeSave()
	stateSinkObject.Save(0, &c.clock)
	stateSinkObject.Save(1, &c.allowPacketEndpointWrite)
	stateSinkObject.Save(2, &c.allowLiveTCPMigration)
	stateSinkObject.Save(3, &c.uid)
	stateSinkObject.Save(4, &c.egressFD)
	stateSinkObject.Save(5, &c.egressGated)
}

// +checklocksignore
func (c *sandboxNetstackCreator) StateLoad(ctx context.Context, stateSourceObject state.Source) {
	stateSourceObject.Load(0, &c.clock)
	stateSourceObject.Load(1, &c.allowPacketEndpointWrite)
	stateSourceObject.Load(2, &c.allowLiveTCPMigration)
	stateSourceObject.Load(3, &c.uid)
	stateSourceObject.Load(4, &c.egressFD)
	stateSourceObject.Load(5, &c.egressGated)
	stateSourceObject.AfterLoad(func() { c.afterLoad(ctx) })
}

func init() {
	state.Register((*sandboxNetstackCreator)(nil))
}
